# Generated by Django 6.0.3 on 2026-04-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_globalconfig_coupon_is_free_delivery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalconfig',
            options={'verbose_name': 'Global Configuration', 'verbose_name_plural': 'Global Configurations'},
        ),
        migrations.RemoveField(
            model_name='globalconfig',
            name='label',
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
