# Generated by Django 6.0.3 on 2026-04-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_globalconfig_options_remove_globalconfig_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. IPL Match Combo', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price for the combo', max_digits=10)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='combos', to='api.menuitem')),
            ],
            options={
                'verbose_name': 'Predefined Combo',
                'verbose_name_plural': 'Predefined Combos',
            },
        ),
    ]
