# Generated by Django 6.0.3 on 2026-04-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_predefinedcombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedcombo',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predefined_combos', to='api.restaurant'),
        ),
    ]
