# Generated by Django 6.0.3 on 2026-04-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_predefinedcombo_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedcombo',
            name='source_restaurant_name',
            field=models.CharField(blank=True, help_text='Manual restaurant name for display', max_length=200, null=True),
        ),
    ]
