# Generated by Django 6.0.3 on 2026-05-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_riderpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driving_license',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='rider_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
